#!/bin/bash

# THIS WILL BE THE LOCATION OF THE EXECTUABLE THAT WILL BE USED BY
# ALL OF THE BATCH SCRIPTS IN THIS FOLDER
# ONLY UNCOMMENT THE ONE YOU WANT TO USE
# NOTE THAT A LINE IS COMMENTED WHEN IT BEGINS WITH "::"
# THE VARIABLE "OWHM" IS SET TO THE VALUE TO THE RIGHT OF THE "="
# WHICH REPRESENTS THE LOCATION OF OWHM THAT WILL BE USED IN ALL THE BATCH SCRIPTS

SHELLDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

CWD=$(pwd)
cd "$SHELLDIR"
cd ../../bin
BINPATH=$(pwd)

#SELECT VERSION TO USE

# USE OWHM RELEASE VERSION x64 Unix
 OWHM=$BINPATH/OWHM.nix

# USE OWHM DEBUG   VERSION x64
# OWHM=$BINPATH/OWHM_debug.nix

# USE OWHM RELEASE VERSION x64 Win64 REQUIRES WINE/WINEHQ/WINELIB (WINE acronym => Wine Is Not an Emulator)
# OWHM="wine $BINPATH/MF_OWHM.exe"


# SET HYDFMT BINARY LOCATION
  HYDFMT=$BINPATH/Postprocessors/hydfmt.nix
 ZONBUD3=$BINPATH/Postprocessors/zonbud.nix


#RETURN TO CALLING FOLDER
cd "$CWD"

