      MODULE GWFLAKMODULE
!------OLD USGS VERSION 7.1; JUNE 2006 GWFLAKMODULE; 
!------UPDATED FOR MF-2005, 1.9 RELEASE, FEBRUARY 6, 2012  
!------REVISION NUMBER CHANGED TO BE CONSISTENT WITH NWT RELEASE
!------NEW VERSION NUMBER 1.1.2, 9/15/2016  
!------MINOR UPDATES JAN. 2013 (LFK)
        USE BUDGET_GROUP_INTERFACE, ONLY: BUDGET_GROUP
        PRIVATE:: BUDGET_GROUP
        !
        INTEGER,SAVE,POINTER:: IOUT, LOUT
        !
        CHARACTER(LEN=64),PARAMETER::Version_lak = '$Id: gwf2lak7_NWT.f 2370 2014-07-01 17:35:48Z rniswon $'
        INTEGER,          SAVE,                   POINTER:: NLAKES,NLAKESAR,ILKCB,NSSITR,LAKUNIT
        INTEGER,          SAVE,                   POINTER:: MXLKND,LKNODE,ICMX,NCLS,LWRT,NDV,NTRB,IRDTAB
        REAL,             SAVE,                   POINTER::THETA,SSCNCR,SURFDEPTH
!dep    Added SURFDEPTH  3/3/2009
!rgn    Added budget variables for GSFLOW CSV file
        REAL,             SAVE,                   POINTER:: TOTGWIN_LAK,TOTGWOT_LAK,TOTDELSTOR_LAK
        REAL,             SAVE,                   POINTER:: TOTSTOR_LAK,TOTEVAP_LAK,TOTPPT_LAK
        REAL,             SAVE,                   POINTER:: TOTRUNF_LAK,TOTWTHDRW_LAK,TOTSURFIN_LAK
        REAL,             SAVE,                   POINTER:: TOTSURFOT_LAK
        INTEGER,          SAVE, DIMENSION(:),     POINTER, CONTIGUOUS:: ICS, NCNCVR, LIMERR, LAKTAB
        INTEGER,          SAVE, DIMENSION(:,:),   POINTER, CONTIGUOUS:: ILAKE,ITRB,IDIV,ISUB,IRK
        INTEGER,          SAVE, DIMENSION(:,:,:), POINTER, CONTIGUOUS:: LKARR1
        REAL,             SAVE, DIMENSION(:),     POINTER, CONTIGUOUS:: STAGES
        DOUBLE PRECISION, SAVE, DIMENSION(:),     POINTER, CONTIGUOUS:: STGNEW,STGOLD,STGITER,VOLOLDD,STGOLD2
        DOUBLE PRECISION, SAVE, DIMENSION(:),     POINTER:: RUNF, RUNOFF     !EDM
        INTEGER,          SAVE,                   POINTER:: NLKFLWTYP
        CHARACTER*16,     SAVE, DIMENSION(:),     POINTER, CONTIGUOUS:: LKFLOWTYPE
        REAL,             SAVE, DIMENSION(:),     POINTER, CONTIGUOUS:: VOL,FLOB,DSRFOT
        DOUBLE PRECISION, SAVE, DIMENSION(:),     POINTER, CONTIGUOUS:: PRCPLK,EVAPLK
        REAL,             SAVE, DIMENSION(:),     POINTER, CONTIGUOUS:: BEDLAK
        REAL,             SAVE, DIMENSION(:),     POINTER, CONTIGUOUS:: WTHDRW,RNF,CUMRNF
        REAL,             SAVE, DIMENSION(:),     POINTER, CONTIGUOUS:: CUMPPT,CUMEVP,CUMGWI
        REAL,             SAVE, DIMENSION(:),     POINTER, CONTIGUOUS:: CUMUZF
        REAL,             SAVE, DIMENSION(:),     POINTER, CONTIGUOUS:: CUMGWO,CUMSWI,CUMSWO
        REAL,             SAVE, DIMENSION(:),     POINTER, CONTIGUOUS:: CUMWDR,CUMFLX,CNDFCT
        REAL,             SAVE, DIMENSION(:),     POINTER, CONTIGUOUS:: VOLINIT
        REAL,             SAVE, DIMENSION(:),     POINTER, CONTIGUOUS:: BOTTMS,BGAREA,SSMN,SSMX
!dep    Added cumulative and time step error budget arrays
        REAL,             SAVE, DIMENSION(:),     POINTER, CONTIGUOUS:: CUMVOL,CMLAKERR,CUMLKOUT
        REAL,             SAVE, DIMENSION(:),     POINTER, CONTIGUOUS:: CUMLKIN,TSLAKERR,DELVOL
!rgn        REAL,   SAVE, DIMENSION(:),  POINTER::EVAP,PRECIP,SEEP,SEEP3
        DOUBLE PRECISION, SAVE, DIMENSION(:),     POINTER, CONTIGUOUS:: EVAP, PRECIP
        DOUBLE PRECISION, SAVE, DIMENSION(:),     POINTER, CONTIGUOUS:: EVAP3, PRECIP3
        DOUBLE PRECISION, SAVE, DIMENSION(:),     POINTER, CONTIGUOUS:: FLWITER
        DOUBLE PRECISION, SAVE, DIMENSION(:),     POINTER, CONTIGUOUS:: FLWITER3
        DOUBLE PRECISION, SAVE, DIMENSION(:),     POINTER, CONTIGUOUS:: SEEP,SEEP3
        DOUBLE PRECISION, SAVE, DIMENSION(:),     POINTER, CONTIGUOUS:: SEEPUZ
        DOUBLE PRECISION, SAVE, DIMENSION(:),     POINTER, CONTIGUOUS:: WITHDRW
        DOUBLE PRECISION, SAVE, DIMENSION(:),     POINTER, CONTIGUOUS:: SURFA
        REAL,             SAVE, DIMENSION(:),     POINTER, CONTIGUOUS:: SURFOT,SURFIN
        REAL,             SAVE, DIMENSION(:),     POINTER, CONTIGUOUS:: SUMCNN,SUMCHN
        REAL,             SAVE, DIMENSION(:,:),   POINTER, CONTIGUOUS:: CLAKE,CRNF,SILLVT
        REAL,             SAVE, DIMENSION(:,:),   POINTER, CONTIGUOUS:: CAUG,CPPT,CLAKINIT
        REAL,             SAVE, DIMENSION(:,:,:), POINTER, CONTIGUOUS:: BDLKN1
!dep  Added arrays for tracking lake budgets for dry lakes
        REAL,             SAVE, DIMENSION(:),     POINTER, CONTIGUOUS:: EVAPO,FLWIN
        REAL,             SAVE, DIMENSION(:),     POINTER, CONTIGUOUS:: GWRATELIM
!dep    Allocate arrays to add runoff from UZF Package
        REAL,             SAVE, DIMENSION(:),     POINTER, CONTIGUOUS:: OVRLNDRNF,CUMLNDRNF
!dep    Allocate arrays for lake depth, area,and volume relations
        DOUBLE PRECISION, SAVE, DIMENSION(:,:),   POINTER, CONTIGUOUS:: DEPTHTABLE
        DOUBLE PRECISION, SAVE, DIMENSION(:,:),   POINTER, CONTIGUOUS:: AREATABLE
        DOUBLE PRECISION, SAVE, DIMENSION(:,:),   POINTER, CONTIGUOUS:: VOLUMETABLE
!dep    Allocate space for three dummy arrays used in GAGE Package
!         when Solute Transport is active
        REAL,             SAVE, DIMENSION(:,:),   POINTER, CONTIGUOUS:: XLAKES,XLAKINIT,XLKOLD
!rsr    Allocate arrays in BD subroutine
        INTEGER,          SAVE, DIMENSION(:),     POINTER, CONTIGUOUS:: LDRY,NCNT,NCNST,KSUB
        INTEGER,          SAVE, DIMENSION(:),     POINTER, CONTIGUOUS:: MSUB1
        INTEGER,          SAVE, DIMENSION(:,:),   POINTER, CONTIGUOUS:: MSUB
        REAL,             SAVE, DIMENSION(:),     POINTER, CONTIGUOUS:: FLXINL,VOLOLD,GWIN,GWOUT
        REAL,             SAVE, DIMENSION(:),     POINTER, CONTIGUOUS:: DELH,TDELH,SVT,STGADJ
        REAL,             SAVE, DIMENSION(:,:),   POINTER, CONTIGUOUS:: LAKSEEP
        INTEGER,          SAVE,                   POINTER:: NSFRLAK                 !EDM
        INTEGER,          SAVE, DIMENSION(:),     POINTER:: LAKSFR,ILKSEG,ILKRCH    !EDM
        REAL,             SAVE, DIMENSION(:),     POINTER:: SWLAK,DELVOLLAK         !EDM
      TYPE GWFLAKTYPE
        INTEGER,      POINTER:: NLAKES,NLAKESAR,ILKCB,NSSITR,LAKUNIT
        INTEGER,      POINTER:: MXLKND,LKNODE,ICMX,NCLS,LWRT,NDV,NTRB,IRDTAB
!dep    Added SURFDEPTH 3/3/2009
        REAL,         POINTER:: THETA,SSCNCR,SURFDEPTH
!rgn    Added budget variables for GSFLOW CSV file
        REAL,                               POINTER:: TOTGWIN_LAK,TOTGWOT_LAK,TOTDELSTOR_LAK
        REAL,                               POINTER:: TOTSTOR_LAK,TOTEVAP_LAK,TOTPPT_LAK
        REAL,                               POINTER:: TOTRUNF_LAK,TOTWTHDRW_LAK
        REAL,                               POINTER:: TOTSURFOT_LAK,TOTSURFIN_LAK
        INTEGER,          DIMENSION(:),     POINTER, CONTIGUOUS::ICS, NCNCVR,LIMERR, LAKTAB
        INTEGER,          DIMENSION(:,:),   POINTER, CONTIGUOUS::ILAKE,ITRB,IDIV,ISUB,IRK
        INTEGER,          DIMENSION(:,:,:), POINTER, CONTIGUOUS::LKARR1
        REAL,             DIMENSION(:),     POINTER, CONTIGUOUS::STAGES
        DOUBLE PRECISION, DIMENSION(:),     POINTER, CONTIGUOUS::STGNEW,STGOLD,STGITER,STGOLD2
        DOUBLE PRECISION, DIMENSION(:),     POINTER:: RUNF, RUNOFF              !EDM
        INTEGER,                            POINTER:: NLKFLWTYP
        CHARACTER*16,     DIMENSION(:),     POINTER, CONTIGUOUS:: LKFLOWTYPE
        DOUBLE PRECISION, DIMENSION(:),     POINTER, CONTIGUOUS:: VOLOLDD
        REAL,             DIMENSION(:),     POINTER, CONTIGUOUS:: VOL,FLOB, DSRFOT
        DOUBLE PRECISION, DIMENSION(:),     POINTER, CONTIGUOUS:: PRCPLK,EVAPLK
        REAL,             DIMENSION(:),     POINTER, CONTIGUOUS:: BEDLAK
        REAL,             DIMENSION(:),     POINTER, CONTIGUOUS:: WTHDRW,RNF,CUMRNF
        REAL,             DIMENSION(:),     POINTER, CONTIGUOUS:: CUMPPT,CUMEVP,CUMGWI
        REAL,             DIMENSION(:),     POINTER, CONTIGUOUS:: CUMUZF
        REAL,             DIMENSION(:),     POINTER, CONTIGUOUS:: CUMGWO,CUMSWI,CUMSWO
        REAL,             DIMENSION(:),     POINTER, CONTIGUOUS:: CUMWDR,CUMFLX,CNDFCT
        REAL,             DIMENSION(:),     POINTER, CONTIGUOUS:: VOLINIT
        REAL,             DIMENSION(:),     POINTER, CONTIGUOUS:: BOTTMS,BGAREA,SSMN,SSMX
!dep    Added cumulative and time step error budget arrays
        REAL,             DIMENSION(:),     POINTER, CONTIGUOUS:: CUMVOL,CMLAKERR,CUMLKOUT
        REAL,             DIMENSION(:),     POINTER, CONTIGUOUS:: TSLAKERR,DELVOL,CUMLKIN
!rgn        REAL,         DIMENSION(:),  POINTER::EVAP,PRECIP,SEEP,SEEP3
        DOUBLE PRECISION, DIMENSION(:),     POINTER, CONTIGUOUS:: EVAP,PRECIP
        DOUBLE PRECISION, DIMENSION(:),     POINTER, CONTIGUOUS:: EVAP3,PRECIP3
        DOUBLE PRECISION, DIMENSION(:),     POINTER, CONTIGUOUS:: FLWITER
        DOUBLE PRECISION, DIMENSION(:),     POINTER, CONTIGUOUS:: FLWITER3
        DOUBLE PRECISION, DIMENSION(:),     POINTER, CONTIGUOUS:: SEEP,SEEP3
        DOUBLE PRECISION, DIMENSION(:),     POINTER, CONTIGUOUS:: SEEPUZ
        DOUBLE PRECISION, DIMENSION(:),     POINTER, CONTIGUOUS:: WITHDRW  
        DOUBLE PRECISION, DIMENSION(:),     POINTER, CONTIGUOUS:: SURFA
        REAL,             DIMENSION(:),     POINTER, CONTIGUOUS:: SURFIN,SURFOT
        REAL,             DIMENSION(:),     POINTER, CONTIGUOUS:: SUMCNN,SUMCHN
        REAL,             DIMENSION(:,:),   POINTER, CONTIGUOUS:: CLAKE,CRNF,SILLVT
        REAL,             DIMENSION(:,:),   POINTER, CONTIGUOUS:: CAUG,CPPT,CLAKINIT
        REAL,             DIMENSION(:,:,:), POINTER, CONTIGUOUS:: BDLKN1
!dep  Added arrays for tracking lake budgets for dry lakes
        REAL,             DIMENSION(:),     POINTER, CONTIGUOUS:: EVAPO,FLWIN
        REAL,             DIMENSION(:),     POINTER, CONTIGUOUS:: GWRATELIM
!dep    Allocate arrays to add runoff from UZF Package
        REAL,             DIMENSION(:),     POINTER, CONTIGUOUS:: OVRLNDRNF,CUMLNDRNF
!dep    Allocate arrays for lake depth, area, and volume relations
        DOUBLE PRECISION, DIMENSION(:,:),   POINTER, CONTIGUOUS:: DEPTHTABLE
        DOUBLE PRECISION, DIMENSION(:,:),   POINTER, CONTIGUOUS:: AREATABLE
        DOUBLE PRECISION, DIMENSION(:,:),   POINTER, CONTIGUOUS:: VOLUMETABLE
!dep    Allocate space for three dummy arrays used in GAGE Package
!         when Solute Transport is active
        REAL,             DIMENSION(:,:),   POINTER, CONTIGUOUS:: XLAKES,XLAKINIT,XLKOLD
!rsr    Allocate arrays in BD subroutine
        INTEGER,          DIMENSION(:),     POINTER, CONTIGUOUS:: LDRY,NCNT,NCNST,KSUB
        INTEGER,          DIMENSION(:),     POINTER, CONTIGUOUS:: MSUB1
        INTEGER,          DIMENSION(:,:),   POINTER, CONTIGUOUS:: MSUB
        REAL,             DIMENSION(:),     POINTER, CONTIGUOUS:: FLXINL,VOLOLD,GWIN,GWOUT
        REAL,             DIMENSION(:),     POINTER, CONTIGUOUS:: DELH,TDELH,SVT,STGADJ
        REAL,             DIMENSION(:,:),   POINTER, CONTIGUOUS:: LAKSEEP
        INTEGER,                            POINTER:: NSFRLAK                 !EDM
        INTEGER,          DIMENSION(:),     POINTER, CONTIGUOUS:: LAKSFR,ILKSEG,ILKRCH    !EDM
        REAL,             DIMENSION(:),     POINTER, CONTIGUOUS:: SWLAK,DELVOLLAK         !EDM
      END TYPE
      TYPE(GWFLAKTYPE), SAVE:: GWFLAKDAT(10)
      END MODULE GWFLAKMODULE
