      MODULE GWFUZFMODULE
        USE BUDGET_GROUP_INTERFACE, ONLY: BUDGET_GROUP
        PRIVATE:: BUDGET_GROUP
        !
        INTEGER,SAVE,POINTER:: IOUT, LOUT
        !
        CHARACTER(LEN=64):: Version_uzf
        REAL,                 PARAMETER:: CLOSEZERO=1.0E-15
        DOUBLE PRECISION,     PARAMETER:: NEARZERO=1.0D-30
        DOUBLE PRECISION,     PARAMETER:: ZEROD15=1.0D-15, ZEROD9=1.0D-09
        DOUBLE PRECISION,     PARAMETER:: ZEROD6=1.0D-06
        DOUBLE PRECISION,     PARAMETER:: ZEROD7=1.0D-07, ZEROD5=1.0D-05
        INTEGER,              PARAMETER:: IRUNBIG = 10000
        INTEGER,          SAVE,                   POINTER:: NUMCELLS, TOTCELLS, Iseepsupress
        INTEGER,          SAVE,                   POINTER :: ISAVEFINF
        INTEGER,          SAVE,                   POINTER:: IPRCNT, Ireadsurfk, Isurfkreject
        INTEGER,          SAVE,                   POINTER:: Iseepreject
        INTEGER,          SAVE,                   POINTER:: ITHTIFLG, ITHTRFLG, UNITRECH, UNITDIS
        DOUBLE PRECISION, SAVE,                   POINTER:: THETAB, FLUXB, FLUXHLD2                    !seb added POINTER
        DOUBLE PRECISION, SAVE, DIMENSION(:),     POINTER, CONTIGUOUS:: CHECKTIME
        INTEGER,          SAVE, DIMENSION(:),     POINTER, CONTIGUOUS:: MORE
        INTEGER,          SAVE, DIMENSION(:,:),   POINTER, CONTIGUOUS:: LAYNUM
        INTEGER,          SAVE,                   POINTER:: NUZTOP, IUZFOPT, IRUNFLG, IETFLG, IUZM
        INTEGER,          SAVE,                   POINTER:: IUZFCB1, IUZFCB2, NTRAIL, NWAV, NSETS
        INTEGER,          SAVE,                   POINTER:: IUZFB22, IUZFB11, ETOPT
        INTEGER,          SAVE,                   POINTER:: NUZGAG, NUZGAGAR, NUZCL, NUZRW, IGSFLOW
        INTEGER,          SAVE,                   POINTER:: RTSOLUTE, IETBUD, INETFLUX, ETOFH_FLAG
        INTEGER,          SAVE, DIMENSION(:),     POINTER, CONTIGUOUS:: ITRLSTH
        INTEGER,          SAVE, DIMENSION(:,:),   POINTER, CONTIGUOUS:: IRUNBND, IUZFBND
        INTEGER,          SAVE, DIMENSION(:,:),   POINTER, CONTIGUOUS:: IUZLIST, NWAVST
        INTEGER,          SAVE, DIMENSION(:,:),   POINTER, CONTIGUOUS:: IUZHOLD
        INTEGER,          SAVE, DIMENSION(:,:),   POINTER, CONTIGUOUS:: LTRLST, ITRLST
        INTEGER,          SAVE, DIMENSION(:),     POINTER, CONTIGUOUS:: LTRLIT, ITRLIT
        REAL,             SAVE,                   POINTER::             TOTRUNOFF, SURFDEP
        REAL,             SAVE, DIMENSION(:),     POINTER, CONTIGUOUS:: FBINS
        REAL,             SAVE, DIMENSION(:,:),   POINTER, CONTIGUOUS:: SEEPOUT, EXCESPP, VKS
        REAL,             SAVE, DIMENSION(:,:),   POINTER, CONTIGUOUS:: SURFK
        REAL,             SAVE, DIMENSION(:,:),   POINTER, CONTIGUOUS:: AIR_ENTRY, H_ROOT
        REAL,             SAVE, DIMENSION(:,:),   POINTER, CONTIGUOUS:: REJ_INF
        REAL,             SAVE, DIMENSION(:,:),   POINTER, CONTIGUOUS:: TO_CFP
        REAL,             SAVE, DIMENSION(:,:),   POINTER, CONTIGUOUS:: EPS, THTS, THTI, THTR
        REAL,             SAVE, DIMENSION(:,:),   POINTER, CONTIGUOUS:: PETRATE, ROOTDPTH
        REAL,             SAVE, DIMENSION(:,:),   POINTER, CONTIGUOUS:: WCWILT,FINF,FINFSAVE
        REAL,             SAVE, DIMENSION(:,:),   POINTER, CONTIGUOUS:: UZFETOUT, GWET
        REAL,             SAVE, DIMENSION(:,:),   POINTER, CONTIGUOUS:: FNETEXFIL1
        REAL,             SAVE, DIMENSION(:,:),   POINTER, CONTIGUOUS:: FNETEXFIL2
        REAL,             SAVE, DIMENSION(:,:),   POINTER, CONTIGUOUS:: CUMGWET
        REAL,             SAVE,                   POINTER::             TIMEPRINT
        DOUBLE PRECISION, SAVE,                   POINTER::             SMOOTHET
        DOUBLE PRECISION, SAVE, DIMENSION(:),     POINTER, CONTIGUOUS:: CUMUZVOL 
        DOUBLE PRECISION, SAVE, DIMENSION(:),     POINTER, CONTIGUOUS:: UZTSRAT
        DOUBLE PRECISION, SAVE, DIMENSION(:,:),   POINTER, CONTIGUOUS:: UZFLWT, UZSTOR
        DOUBLE PRECISION, SAVE, DIMENSION(:,:),   POINTER, CONTIGUOUS:: UZDPST, UZTHST
        DOUBLE PRECISION, SAVE, DIMENSION(:),     POINTER, CONTIGUOUS:: UZDPIT, UZTHIT
        DOUBLE PRECISION, SAVE, DIMENSION(:,:),   POINTER, CONTIGUOUS:: UZSPST, UZFLST
        DOUBLE PRECISION, SAVE, DIMENSION(:),     POINTER, CONTIGUOUS:: UZSPIT, UZFLIT
        DOUBLE PRECISION, SAVE, DIMENSION(:,:),   POINTER, CONTIGUOUS:: DELSTOR
        DOUBLE PRECISION, SAVE, DIMENSION(:,:),   POINTER, CONTIGUOUS:: UZOLSFLX
        DOUBLE PRECISION, SAVE, DIMENSION(:,:),   POINTER, CONTIGUOUS:: HLDUZF
        DOUBLE PRECISION, SAVE, DIMENSION(:,:),   POINTER, CONTIGUOUS:: RTSOLWC
        DOUBLE PRECISION, SAVE, DIMENSION(:,:),   POINTER, CONTIGUOUS:: RTSOLFL
        DOUBLE PRECISION, SAVE, DIMENSION(:,:),   POINTER, CONTIGUOUS:: RTSOLDS
        DOUBLE PRECISION, SAVE, DIMENSION(:,:,:), POINTER, CONTIGUOUS:: UZTOTBAL
        DOUBLE PRECISION, SAVE, DIMENSION(:,:,:), POINTER, CONTIGUOUS:: GRIDSTOR
        DOUBLE PRECISION, SAVE, DIMENSION(:,:,:), POINTER, CONTIGUOUS:: GRIDET
      TYPE GWFUZFTYPE
        !
        INTEGER,POINTER:: IOUT, LOUT
        !
        INTEGER,                            POINTER:: NUZTOP, IUZFOPT, IRUNFLG, IETFLG, IUZM
        INTEGER,                            POINTER:: IUZFCB1, IUZFCB2, NTRAIL, NWAV, NSETS
        INTEGER,                            POINTER:: IUZFB22, IUZFB11, ETOPT
        INTEGER,                            POINTER:: NUZGAG, NUZGAGAR, NUZCL, NUZRW, IGSFLOW
        INTEGER,                            POINTER:: RTSOLUTE, IETBUD, INETFLUX, ETOFH_FLAG
        INTEGER,                            POINTER:: NUMCELLS, TOTCELLS, Iseepsupress
        INTEGER,                            POINTER :: ISAVEFINF
        INTEGER,                            POINTER:: IPRCNT, Ireadsurfk, Isurfkreject
        INTEGER,                            POINTER:: Iseepreject
        INTEGER,                            POINTER:: ITHTIFLG, ITHTRFLG, UNITRECH, UNITDIS
        DOUBLE PRECISION,                   POINTER:: THETAB, FLUXB, FLUXHLD2               !seb added POINTER
        DOUBLE PRECISION, DIMENSION(:),     POINTER, CONTIGUOUS:: CHECKTIME
        INTEGER,          DIMENSION(:),     POINTER, CONTIGUOUS:: MORE
        INTEGER,          DIMENSION(:,:),   POINTER, CONTIGUOUS:: LAYNUM
        INTEGER,          DIMENSION(:),     POINTER, CONTIGUOUS:: ITRLSTH
        INTEGER,          DIMENSION(:,:),   POINTER, CONTIGUOUS:: IRUNBND, IUZFBND
        INTEGER,          DIMENSION(:,:),   POINTER, CONTIGUOUS:: IUZLIST, NWAVST
        INTEGER,          DIMENSION(:,:),   POINTER, CONTIGUOUS:: IUZHOLD
        INTEGER,          DIMENSION(:,:),   POINTER, CONTIGUOUS:: LTRLST, ITRLST
        INTEGER,          DIMENSION(:),     POINTER, CONTIGUOUS:: LTRLIT, ITRLIT
        REAL,                               POINTER          ::TOTRUNOFF, SURFDEP
        REAL,             DIMENSION(:),     POINTER, CONTIGUOUS:: FBINS
        REAL,             DIMENSION(:,:),   POINTER, CONTIGUOUS:: SEEPOUT, EXCESPP, VKS
        REAL,             DIMENSION(:,:),   POINTER, CONTIGUOUS:: SURFK
        REAL,             DIMENSION(:,:),   POINTER, CONTIGUOUS:: AIR_ENTRY, H_ROOT
        REAL,             DIMENSION(:,:),   POINTER, CONTIGUOUS:: REJ_INF
        REAL,             DIMENSION(:,:),   POINTER, CONTIGUOUS:: TO_CFP
        REAL,             DIMENSION(:,:),   POINTER, CONTIGUOUS:: EPS, THTS, THTI, THTR
        REAL,             DIMENSION(:,:),   POINTER, CONTIGUOUS:: PETRATE, ROOTDPTH
        REAL,             DIMENSION(:,:),   POINTER, CONTIGUOUS:: WCWILT, FINF,FINFSAVE
        REAL,             DIMENSION(:,:),   POINTER, CONTIGUOUS:: UZFETOUT, GWET
        REAL,             DIMENSION(:,:),   POINTER, CONTIGUOUS:: FNETEXFIL1
        REAL,             DIMENSION(:,:),   POINTER, CONTIGUOUS:: FNETEXFIL2, CUMGWET
        REAL,                               POINTER:: TIMEPRINT
        DOUBLE PRECISION,                   POINTER:: SMOOTHET
        DOUBLE PRECISION, DIMENSION(:),     POINTER, CONTIGUOUS:: CUMUZVOL
        DOUBLE PRECISION, DIMENSION(:),     POINTER, CONTIGUOUS:: UZTSRAT
        DOUBLE PRECISION, DIMENSION(:,:),   POINTER, CONTIGUOUS:: UZFLWT, UZSTOR
        DOUBLE PRECISION, DIMENSION(:,:),   POINTER, CONTIGUOUS:: UZDPST, UZTHST
        DOUBLE PRECISION, DIMENSION(:),     POINTER, CONTIGUOUS:: UZDPIT, UZTHIT
        DOUBLE PRECISION, DIMENSION(:,:),   POINTER, CONTIGUOUS:: UZSPST, UZFLST
        DOUBLE PRECISION, DIMENSION(:),     POINTER, CONTIGUOUS:: UZSPIT, UZFLIT
        DOUBLE PRECISION, DIMENSION(:,:),   POINTER, CONTIGUOUS:: DELSTOR
        DOUBLE PRECISION, DIMENSION(:,:),   POINTER, CONTIGUOUS:: UZOLSFLX
        DOUBLE PRECISION, DIMENSION(:,:),   POINTER, CONTIGUOUS:: HLDUZF
        DOUBLE PRECISION, DIMENSION(:,:),   POINTER, CONTIGUOUS:: RTSOLWC
        DOUBLE PRECISION, DIMENSION(:,:),   POINTER, CONTIGUOUS:: RTSOLFL
        DOUBLE PRECISION, DIMENSION(:,:),   POINTER, CONTIGUOUS:: RTSOLDS
        DOUBLE PRECISION, DIMENSION(:,:,:), POINTER, CONTIGUOUS:: UZTOTBAL
        DOUBLE PRECISION, DIMENSION(:,:,:), POINTER, CONTIGUOUS:: GRIDSTOR
        DOUBLE PRECISION, DIMENSION(:,:,:), POINTER, CONTIGUOUS:: GRIDET
      END TYPE
      TYPE(GWFUZFTYPE), SAVE:: GWFUZFDAT(10)
      END MODULE GWFUZFMODULE