70   11   7   0   0   0  0.0   0.2   5   -1   -1   1     Line 1: ISUBCB ISUBOC NNDB NDB NMZ NN AC1 AC2 ITMIN IDSAVE IDREST  SUBLNK 
1 2 3 4 5 6 7                                            Line 2: no delay layer assignment IBQ for each layer    (no line 3 or 4 or 9 (or 10 -14), NDB = 0)
OPEN/CLOSE ./DATA/crt_hd_01.txt 1.000000E-00 (FREE) -1   Line 5: HC: OPEN/CLOSE CNSTNT FMTIN IPRN HC Layer 1
constant 5.025E-004 (FREE) -1                            Line 6: Sfe Layer 1 HERE: SSKE=6e-6, AVGTHK=83.75
constant 5.025E-002 (FREE) -1                            Line 7: Sfv Layer 1 HERE: SSKV=6e-4, AVGTHK=83.75
         0     0.000                                     ND STRT ELAS COMPACTION FOR LAYER   1
         0     0.000                                     ND STRT VIRG COMPACTION FOR LAYER   1
OPEN/CLOSE ./DATA/crt_hd_02.txt 1.000000E-00 (FREE) -1   Line 5: HC: OPEN/CLOSE CNSTNT FMTIN IPRN HC Layer 2
constant 1.5E-005  (FREE) -1                             Line 6: Sfe Layer 2 HERE: SSKE=3e-6, THK=5
constant 1.5E-003  (FREE) -1                             Line 7: Sfv Layer 2 HERE: SSKV=3e-4, THK=5
         0     0.000                                     ND STRT ELAS COMPACTION FOR LAYER   2
         0     0.000                                     ND STRT VIRG COMPACTION FOR LAYER   2
OPEN/CLOSE ./DATA/crt_hd_03.txt 1.000000E-00 (FREE) -1   Line 5: HC: OPEN/CLOSE CNSTNT FMTIN IPRN HC Layer 3
constant 3.6E-004  (FREE) -1                             Line 6: Sfe Layer 3 HERE: SSKE=6e-6, THK=60
constant 3.6E-002  (FREE) -1                             Line 7: Sfv Layer 3 HERE: SSKV=6e-4, THK=60
         0     0.000                                     ND STRT ELAS COMPACTION FOR LAYER   3
         0     0.000                                     ND STRT VIRG COMPACTION FOR LAYER   3         
OPEN/CLOSE ./DATA/crt_hd_04.txt 1.000000E-00 (FREE) -1   Line 5: HC: OPEN/CLOSE CNSTNT FMTIN IPRN HC Layer 4
constant 4.5E-005  (FREE) -1                             Line 6: Sfe Layer 4 HERE: SSKE=3e-6, THK=15
constant 4.5E-003  (FREE) -1                             Line 7: Sfv Layer 4 HERE: SSKV=3e-4, THK=15
         0     0.000                                     ND STRT ELAS COMPACTION FOR LAYER   4
         0     0.000                                     ND STRT VIRG COMPACTION FOR LAYER   4
OPEN/CLOSE ./DATA/crt_hd_05.txt 1.000000E-00 (FREE) -1   Line 5: HC: OPEN/CLOSE CNSTNT FMTIN IPRN HC Layer 5
constant 3.6E-004  (FREE) -1                             Line 6: Sfe Layer 5 HERE: SSKE=6e-6, THK=60
constant 3.6E-002  (FREE) -1                             Line 7: Sfv Layer 5 HERE: SSKV=6e-4, THK=60
         0     0.000                                     ND STRT ELAS COMPACTION FOR LAYER   5
         0     0.000                                     ND STRT VIRG COMPACTION FOR LAYER   5
OPEN/CLOSE ./DATA/crt_hd_06.txt 1.000000E-00 (FREE) -1   Line 5: HC: OPEN/CLOSE CNSTNT FMTIN IPRN HC Layer 6
constant 1.5E-005  (FREE) -1                             Line 6: Sfe Layer 6 HERE: SSKE=3e-6, THK=5
constant 1.5E-003  (FREE) -1                             Line 7: Sfv Layer 6 HERE: SSKV=3e-4, THK=5
         0     0.000                                     ND STRT ELAS COMPACTION FOR LAYER   6
         0     0.000                                     ND STRT VIRG COMPACTION FOR LAYER   6
OPEN/CLOSE ./DATA/crt_hd_07.txt 1.000000E-00 (FREE) -1   Line 5: HC: OPEN/CLOSE CNSTNT FMTIN IPRN HC Layer 7
constant 3.6E-004  (FREE) -1                             Line 6: Sfe Layer 7 HERE: SSKE=6e-6, THK=60
constant 3.6E-002  (FREE) -1                             Line 7: Sfv Layer 7 HERE: SSKV=6e-4, THK=60
         0     0.000                                     ND STRT ELAS COMPACTION FOR LAYER   7
         0     0.000                                     ND STRT VIRG COMPACTION FOR LAYER   7
 10 73  11 74  0 0  0 74  4 75  0 0  0 76  0 77  0 78  0 79       Line 17:  Ifm1 Iun1 Ifm2 Iun2 Ifm3 Iun3 Ifm4 Iun4 Ifm5 Iun5 Ifm6 Iun6 Ifm7 Iun7 Ifm8 Iun8 Ifm9 Iun9 Ifm10 Iun10   
  2   2 10 10  1 1   0 0   0 0   1 0   0 0   0 0   0     0 1   0 0   0 0   0 0    Line 18:  ISP1 ISP2 ITS1 ITS2 Ifl1 Ifl2 Ifl3 Ifl4 Ifl5 Ifl6 Ifl7 Ifl8 Ifl9 Ifl10 Ifl11 Ifl12 Ifl13 Ifl14 Ifl15 Ifl16 Ifl17 Ifl18 Ifl19 Ifl20 Ifl21 
 19  19 10 10  1 1   0 0   0 0   1 0   0 0   0 0   0     0 1   0 0   0 0   0 0    Line 18:  ISP1 ISP2 ITS1 ITS2 Ifl1 Ifl2 Ifl3 Ifl4 Ifl5 Ifl6 Ifl7 Ifl8 Ifl9 Ifl10 Ifl11 Ifl12 Ifl13 Ifl14 Ifl15 Ifl16 Ifl17 Ifl18 Ifl19 Ifl20 Ifl21 
 31  31 10 10  1 1   0 0   0 0   1 0   0 0   0 0   0     0 1   0 0   0 0   0 0    Line 18:  ISP1 ISP2 ITS1 ITS2 Ifl1 Ifl2 Ifl3 Ifl4 Ifl5 Ifl6 Ifl7 Ifl8 Ifl9 Ifl10 Ifl11 Ifl12 Ifl13 Ifl14 Ifl15 Ifl16 Ifl17 Ifl18 Ifl19 Ifl20 Ifl21 
 43  43 10 10  1 1   0 0   0 0   1 0   0 0   0 0   0     0 1   0 0   0 0   0 0    Line 18:  ISP1 ISP2 ITS1 ITS2 Ifl1 Ifl2 Ifl3 Ifl4 Ifl5 Ifl6 Ifl7 Ifl8 Ifl9 Ifl10 Ifl11 Ifl12 Ifl13 Ifl14 Ifl15 Ifl16 Ifl17 Ifl18 Ifl19 Ifl20 Ifl21 
 55  55 10 10  1 1   0 0   0 0   1 0   0 0   0 0   0     0 1   0 0   0 0   0 0    Line 18:  ISP1 ISP2 ITS1 ITS2 Ifl1 Ifl2 Ifl3 Ifl4 Ifl5 Ifl6 Ifl7 Ifl8 Ifl9 Ifl10 Ifl11 Ifl12 Ifl13 Ifl14 Ifl15 Ifl16 Ifl17 Ifl18 Ifl19 Ifl20 Ifl21 
 67  67 10 10  1 1   0 0   0 0   1 0   0 0   0 0   0     0 1   0 0   0 0   0 0    Line 18:  ISP1 ISP2 ITS1 ITS2 Ifl1 Ifl2 Ifl3 Ifl4 Ifl5 Ifl6 Ifl7 Ifl8 Ifl9 Ifl10 Ifl11 Ifl12 Ifl13 Ifl14 Ifl15 Ifl16 Ifl17 Ifl18 Ifl19 Ifl20 Ifl21 
 79  79 10 10  1 1   0 0   0 0   1 0   0 0   0 0   0     0 1   0 0   0 0   0 0    Line 18:  ISP1 ISP2 ITS1 ITS2 Ifl1 Ifl2 Ifl3 Ifl4 Ifl5 Ifl6 Ifl7 Ifl8 Ifl9 Ifl10 Ifl11 Ifl12 Ifl13 Ifl14 Ifl15 Ifl16 Ifl17 Ifl18 Ifl19 Ifl20 Ifl21 
 91  91 10 10  1 1   0 0   0 0   1 0   0 0   0 0   0     0 1   0 0   0 0   0 0    Line 18:  ISP1 ISP2 ITS1 ITS2 Ifl1 Ifl2 Ifl3 Ifl4 Ifl5 Ifl6 Ifl7 Ifl8 Ifl9 Ifl10 Ifl11 Ifl12 Ifl13 Ifl14 Ifl15 Ifl16 Ifl17 Ifl18 Ifl19 Ifl20 Ifl21 
103 103 10 10  1 1   0 0   0 0   1 0   0 0   0 0   0     0 1   0 0   0 0   0 0    Line 18:  ISP1 ISP2 ITS1 ITS2 Ifl1 Ifl2 Ifl3 Ifl4 Ifl5 Ifl6 Ifl7 Ifl8 Ifl9 Ifl10 Ifl11 Ifl12 Ifl13 Ifl14 Ifl15 Ifl16 Ifl17 Ifl18 Ifl19 Ifl20 Ifl21 
115 115 10 10  1 1   0 0   0 0   1 0   0 0   0 0   0     0 1   0 0   0 0   0 0    Line 18:  ISP1 ISP2 ITS1 ITS2 Ifl1 Ifl2 Ifl3 Ifl4 Ifl5 Ifl6 Ifl7 Ifl8 Ifl9 Ifl10 Ifl11 Ifl12 Ifl13 Ifl14 Ifl15 Ifl16 Ifl17 Ifl18 Ifl19 Ifl20 Ifl21 
121 121 10 10  1 1   3 0   0 0   4 0   5 0   0 0   0     6 6   7 0   8 0   9 0     Line 18:  ISP1 ISP2 ITS1 ITS2 Ifl1 Ifl2 Ifl3 Ifl4 Ifl5 Ifl6 Ifl7 Ifl8 Ifl9 Ifl10 Ifl11 Ifl12 Ifl13 Ifl14 Ifl15 Ifl16 Ifl17 Ifl18 Ifl19 Ifl20 Ifl21 

             Ifl1   Ifl3   Ifl5  Ifl7  Ifl9  Ifl11 Ifl13 Ifl14  Ifl16  Ifl18  Ifl20 
               Ifl2   Ifl4   Ifl6  Ifl8 Ifl10 Ifl12      Ifl15   Ifl17  Ifl19   Ifl21