      MODULE GWFSFRMODULE
        USE TABLEFILE_INTERFACE,ONLY:TABFILETYPE1IDX                    !seb
        CHARACTER(LEN=64), SAVE :: Version_sfr
        CHARACTER(LEN=16), SAVE,DIMENSION(:),POINTER,CONTIGUOUS:: SFRAUX
        DOUBLE PRECISION,PARAMETER :: NEARZERO=1.0D-30
        DOUBLE PRECISION,SAVE :: THETAB, FLUXB, FLUXHLD2
        REAL,PARAMETER :: CLOSEZERO=1.0E-15
        INTEGER, SAVE :: Nfoldflbt, NUMTAB, MAXVAL
        INTEGER,SAVE,                 POINTER:: IDVFLG   !diverison recharge is active flag
        INTEGER,SAVE,  DIMENSION(:),  POINTER,CONTIGUOUS:: DVRCH   !(diverted recharge flag; then reharge cell count)
        INTEGER,SAVE,  DIMENSION(:,:,:),POINTER,CONTIGUOUS:: DVRCELL !(store cells to apply diverted recharge)
        REAL,   SAVE,  DIMENSION(:,:),POINTER,CONTIGUOUS:: RECHSAVE  !(store original recharge values)
        REAL,   SAVE,  DIMENSION(:,:),POINTER,CONTIGUOUS:: DVRPERC  !(Percentage of diversion applied to each cell)
        REAL,   SAVE,  DIMENSION(:),POINTER,CONTIGUOUS:: DVEFF  !(store efficiency factor)
        INTEGER,SAVE,POINTER:: NSS, NSTRM, NSFRPAR, ISTCB1, ISTCB2
        INTEGER,SAVE,POINTER:: IUZT, MAXPTS, IRTFLG, NUMTIM, NSEGDIM
        INTEGER,SAVE,POINTER:: ISFROPT, NSTRAIL, ISUZN, NSFRSETS
        INTEGER,SAVE,POINTER:: NUZST, NSTOTRL, NUMAVE, NSFRAUX
        INTEGER,SAVE,POINTER:: ITMP, IRDFLG, IPTFLG, NP
        REAL,   SAVE,POINTER:: CONST, DLEAK, WEIGHT, SFRRATIN, SFRRATOUT
        REAL   ,SAVE,POINTER:: FLWTOL, STRMDELSTOR_CUM, STRMDELSTOR_RATE
        DOUBLE PRECISION,SAVE,POINTER:: TOTSPFLOW
        INTEGER,SAVE,  DIMENSION(:),  POINTER,CONTIGUOUS:: IOTSG, NSEGCK
        INTEGER,SAVE,  DIMENSION(:),  POINTER,CONTIGUOUS:: ITRLSTH
        INTEGER,SAVE,  DIMENSION(:,:),POINTER,CONTIGUOUS:: ISEG, IDIVAR,
     +                                                     ISTRM
        INTEGER,SAVE,  DIMENSION(:,:),POINTER,CONTIGUOUS:: LTRLIT,LTRLST
        INTEGER,SAVE,  DIMENSION(:,:),POINTER,CONTIGUOUS:: ITRLIT,ITRLST
     +                                                   , NWAVST
        REAL,   SAVE,  DIMENSION(:),  POINTER,CONTIGUOUS:: STRIN, STROUT
     +                                                   , FXLKOT
        REAL,   SAVE,  DIMENSION(:),  POINTER,CONTIGUOUS:: UHC, SGOTFLW,
     +                                                     DVRSFLW
        REAL,   SAVE,  DIMENSION(:),  POINTER,CONTIGUOUS:: SFRUZBD
        REAL,   SAVE,  DIMENSION(:,:),POINTER,CONTIGUOUS:: SEG, STRM, 
     +                                                     SFRQ
        REAL,   SAVE,  DIMENSION(:,:),POINTER,CONTIGUOUS:: HWDTH, HWTPRM
        REAL,   SAVE,  DIMENSION(:,:),POINTER,CONTIGUOUS:: QSTAGE, XSEC
        REAL,   SAVE,  DIMENSION(:,:),POINTER,CONTIGUOUS:: AVDPT, AVWAT,
     +                                                     WAT1
        REAL,   SAVE,  DIMENSION(:,:),POINTER,CONTIGUOUS:: CONCQ,
     +                                                  CONCRUN, CONCPPT
        REAL,   SAVE,  DIMENSION(:,:),POINTER,CONTIGUOUS:: TABFLOW, 
     +                                                     TABTIME   !Reading Spedified inflow
        REAL,   SAVE,  DIMENSION(:,:),POINTER,CONTIGUOUS:: FNETSEEP           !writing net seepage in UZF
        INTEGER,SAVE,  DIMENSION(:,:),POINTER,CONTIGUOUS:: ISFRLIST           !Reading Spedified inflow
        DOUBLE PRECISION,SAVE,DIMENSION(:),  POINTER,CONTIGUOUS:: 
     +   THTS,THTR,EPS
        DOUBLE PRECISION,SAVE,DIMENSION(:),  POINTER,CONTIGUOUS:: 
     +   FOLDFLBT, THTI
        DOUBLE PRECISION,SAVE,DIMENSION(:),  POINTER,CONTIGUOUS:: 
     +   SUMLEAK,SUMRCH
        DOUBLE PRECISION,SAVE,DIMENSION(:),  POINTER,CONTIGUOUS:: 
     +   HLDSFR
        DOUBLE PRECISION,SAVE,DIMENSION(:,:),POINTER,CONTIGUOUS:: 
     +   UZFLWT, UZSTOR
        DOUBLE PRECISION,SAVE,DIMENSION(:,:),POINTER,CONTIGUOUS:: 
     +   UZWDTH, UZSEEP
        DOUBLE PRECISION,SAVE,DIMENSION(:,:),POINTER,CONTIGUOUS:: 
     +   DELSTOR, WETPER
        DOUBLE PRECISION,SAVE,DIMENSION(:,:),POINTER,CONTIGUOUS:: 
     +   UZDPIT, UZDPST
        DOUBLE PRECISION,SAVE,DIMENSION(:,:),POINTER,CONTIGUOUS:: 
     +   UZTHIT, UZTHST
        DOUBLE PRECISION,SAVE,DIMENSION(:,:),POINTER,CONTIGUOUS:: 
     +   UZSPIT, UZSPST
        DOUBLE PRECISION,SAVE,DIMENSION(:,:),POINTER,CONTIGUOUS:: 
     +   UZFLIT, UZFLST
        DOUBLE PRECISION,SAVE,DIMENSION(:,:),POINTER,CONTIGUOUS:: 
     +   UZOLSFLX, HSTRM
        DOUBLE PRECISION,SAVE,DIMENSION(:,:),POINTER,CONTIGUOUS:: 
     +   QSTRM, SLKOTFLW
        DOUBLE PRECISION,SAVE,DIMENSION(:,:),POINTER,CONTIGUOUS:: 
     +   DLKOTFLW,DLKSTAGE
        DOUBLE PRECISION,SAVE,DIMENSION(:,:),POINTER,CONTIGUOUS:: 
     +   FINF,RECH
        TYPE(TABFILETYPE1IDX),POINTER,SAVE:: SFRTABFILE                 !seb ADDED TABFILE SUPPORT FROM TABFILE_INTERFACE
      TYPE GWFSFRTYPE
        CHARACTER(LEN=16),    DIMENSION(:),  POINTER,CONTIGUOUS:: SFRAUX
        INTEGER,                      POINTER:: IDVFLG   !diverison recharge is active flag
        INTEGER,       DIMENSION(:),  POINTER,CONTIGUOUS:: DVRCH      !Diversions to recharge
        INTEGER,       DIMENSION(:,:,:),  POINTER,CONTIGUOUS:: DVRCELL  !Diversions to recharge
        REAL,          DIMENSION(:,:),POINTER,CONTIGUOUS:: RECHSAVE  !Diversions to recharge
        REAL,          DIMENSION(:,:),POINTER,CONTIGUOUS:: DVRPERC  !Diversions to recharge
        REAL,          DIMENSION(:),POINTER,CONTIGUOUS:: DVEFF  !Diversions to recharge
        INTEGER,     POINTER:: NSS, NSTRM, NSFRPAR, ISTCB1, ISTCB2
        INTEGER,     POINTER:: IUZT, MAXPTS, IRTFLG, NUMTIM, NSEGDIM
        INTEGER,     POINTER:: ISFROPT, NSTRAIL, ISUZN, NSFRSETS
        INTEGER,     POINTER:: NUZST, NSTOTRL, NUMAVE, NSFRAUX
        INTEGER,     POINTER:: ITMP, IRDFLG, IPTFLG, NP
        REAL,        POINTER:: CONST, DLEAK, WEIGHT, SFRRATIN, SFRRATOUT
        REAL,        POINTER:: FLWTOL, STRMDELSTOR_CUM, STRMDELSTOR_RATE
        DOUBLE PRECISION, POINTER:: TOTSPFLOW
        INTEGER,       DIMENSION(:),  POINTER,CONTIGUOUS:: IOTSG, NSEGCK
        INTEGER,       DIMENSION(:),  POINTER,CONTIGUOUS:: ITRLSTH
        INTEGER,       DIMENSION(:,:),POINTER,CONTIGUOUS:: ISEG, IDIVAR,
     +   ISTRM
        INTEGER,       DIMENSION(:,:),POINTER,CONTIGUOUS:: LTRLIT, 
     +   LTRLST
        INTEGER,       DIMENSION(:,:),POINTER,CONTIGUOUS:: ITRLIT, 
     +   ITRLST, NWAVST
        REAL,          DIMENSION(:),  POINTER,CONTIGUOUS:: STRIN, STROUT
     +   , FXLKOT
        REAL,          DIMENSION(:),  POINTER,CONTIGUOUS:: UHC, SGOTFLW,
     +   DVRSFLW
        REAL,          DIMENSION(:),  POINTER,CONTIGUOUS:: SFRUZBD
        REAL,          DIMENSION(:,:),POINTER,CONTIGUOUS:: SEG, STRM, 
     +   SFRQ
        REAL,          DIMENSION(:,:),POINTER,CONTIGUOUS:: HWDTH, HWTPRM
        REAL,          DIMENSION(:,:),POINTER,CONTIGUOUS:: QSTAGE, XSEC
        REAL,          DIMENSION(:,:),POINTER,CONTIGUOUS:: AVDPT, AVWAT,
     +   WAT1
        REAL,          DIMENSION(:,:),POINTER,CONTIGUOUS:: CONCQ, 
     +   CONCRUN, CONCPPT
        REAL,          DIMENSION(:,:),POINTER,CONTIGUOUS:: TABFLOW, 
     +   TABTIME  ! Reading SPecified inflow
        REAL,          DIMENSION(:,:),POINTER,CONTIGUOUS:: FNETSEEP          !writing net seepage in UZF
        INTEGER,       DIMENSION(:,:),POINTER,CONTIGUOUS:: ISFRLIST
        DOUBLE PRECISION,     DIMENSION(:),  POINTER,CONTIGUOUS:: 
     +   THTS,THTR,EPS
        DOUBLE PRECISION,     DIMENSION(:),  POINTER,CONTIGUOUS:: 
     +   FOLDFLBT, THTI
        DOUBLE PRECISION,     DIMENSION(:),  POINTER,CONTIGUOUS:: 
     +   SUMLEAK, SUMRCH
        DOUBLE PRECISION,     DIMENSION(:),  POINTER,CONTIGUOUS:: 
     +   HLDSFR
        DOUBLE PRECISION,     DIMENSION(:,:),POINTER,CONTIGUOUS:: 
     +   UZFLWT, UZSTOR
        DOUBLE PRECISION,     DIMENSION(:,:),POINTER,CONTIGUOUS:: 
     +   UZWDTH, UZSEEP
        DOUBLE PRECISION,     DIMENSION(:,:),POINTER,CONTIGUOUS:: 
     +   DELSTOR, WETPER
        DOUBLE PRECISION,     DIMENSION(:,:),POINTER,CONTIGUOUS:: 
     +   UZDPIT, UZDPST
        DOUBLE PRECISION,     DIMENSION(:,:),POINTER,CONTIGUOUS:: 
     +   UZTHIT, UZTHST
        DOUBLE PRECISION,     DIMENSION(:,:),POINTER,CONTIGUOUS:: 
     +   UZSPIT, UZSPST
        DOUBLE PRECISION,     DIMENSION(:,:),POINTER,CONTIGUOUS:: 
     +   UZFLIT, UZFLST
        DOUBLE PRECISION,     DIMENSION(:,:),POINTER,CONTIGUOUS:: 
     +   UZOLSFLX, HSTRM
        DOUBLE PRECISION,     DIMENSION(:,:),POINTER,CONTIGUOUS:: 
     +   QSTRM, SLKOTFLW
        DOUBLE PRECISION,     DIMENSION(:,:),POINTER,CONTIGUOUS:: 
     +   DLKOTFLW,DLKSTAGE
        DOUBLE PRECISION,     DIMENSION(:,:),POINTER,CONTIGUOUS:: 
     +   FINF,RECH
        TYPE(TABFILETYPE1IDX),POINTER:: SFRTABFILE                      !seb ADDED TABFILE SUPPORT FROM TABFILE_INTERFACE
      END TYPE
      TYPE(GWFSFRTYPE), SAVE:: GWFSFRDAT(10)
      END MODULE GWFSFRMODULE
